name: sandbox
description: Widgetbook's own "Widgetbook" (i.e. a catalog for widgets built inside Widgetbook).
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.4
  flutter: ^3.38.0

dependencies:
  flutter:
    sdk: flutter

  widgetbook:
    path: ../packages/widgetbook
  widgetbook_annotation:
    path: ../packages/widgetbook_annotation

dev_dependencies:
  alchemist: ^0.11.0
  build_runner: ^2.10.1
  flutter_test:
    sdk: flutter
  widgetbook_generator:
    path: ../packages/widgetbook_generator

flutter:
  uses-material-design: true
